### ISSUE TITLE
test2json: exit status 0xc0000135 in Windows 11

### ISSUE THREAD

**Issue by neetunarayanan** [pact-foundation/pact-workshop-go#22]
Hello Team,

I am trying to run the pact test cases in Windows and getting the following error.

**test2json: exit status 0xc0000135**

Can anyone please give suggestions on how to fix this?

I am using Goland editor and Windows 11 OS.

It works fine in my Ubuntu 22.04.2.

**Comment by YOU54F** [comment]
Hey,

There are some specific pre-reqs for windows, which I have recently added to the README of the pact-go project

https://github.com/pact-foundation/pact-go?tab=readme-ov-file#installation
