### ISSUE TITLE
can-i-deploy step is failing, step11

### ISSUE THREAD

**Issue by fgerner** [pact-foundation/pact-workshop-go#26]
Hi,

I'm having issues on step 11.

running 
```
make deploy-consumer
```
results in
```
--- ✅ Checking if we can deploy consumer
make: pact-broker: No such file or directory
make: *** [deploy-consumer] Error 1
```

**Comment by YOU54F** [comment]
have you installed the cli tools?

https://github.com/pact-foundation/pact-workshop-go/tree/step11?tab=readme-ov-file#publish-from-consumer

**Comment by fgerner** [comment]
yes, 
so I was able to 'make publish' and can see the contracts in the broker ui.
it's the 'can-i-deploy' that's not able to 'find' the published contracts, or something like that.

**Comment by YOU54F** [comment]
ahh okay i can see in the makefile that only the publish command is prefixed with pact/bin/

https://github.com/pact-foundation/pact-workshop-go/blob/d454a6437dfe75f0a9d94b082c6b154cb9d31cd2/Makefile#L65

if you add the same to the other commands they will work.

i’ll update it tomorrow, thanks for letting us know

**Comment by YOU54F** [comment]
the error is it cannot find the executable ( located in pact/bin folder) so it hasn’t even ran the can-i-deploy command.

i probably had the tool already available on my path from separate install which is why it just worked for me

**Comment by YOU54F** [comment]
Updated now, in master branch & step11.

Cheers @fgerner
