### ISSUE TITLE
the 'can-i-deploy' response looks a bit broken.

### ISSUE THREAD

**Issue by fgerner** [pact-foundation/pact-workshop-go#27]
I get a bit unexpected results, following the steps in the readme:

```
% make deploy-consumer
--- ✅ Checking if we can deploy consumer
pact/bin/pact-broker can-i-deploy \
                --pacticipant GoAdminService \
                --broker-base-url http://localhost:8081 \
                --broker-username pact_workshop \
                --broker-password pact_workshop \
                --version d454a6437dfe75f0a9d94b082c6b154cb9d31cd2 \
                --to-environment production
Computer says no ¯\_(ツ)_/¯

CONSUMER       | C.VERSION  | PROVIDER      | P.VERSION | SUCCESS? | RESULT#
---------------|------------|---------------|-----------|----------|--------
GoAdminService | d454a64... | GoUserService | ???       | ???      |        

There is no verified pact between version d454a6437dfe75f0a9d94b082c6b154cb9d31cd2 of GoAdminService and a version of GoUserService currently in production (no version is currently recorded as deployed/released in this environment)
make: *** [deploy-consumer] Error 1

% make deploy-provider
--- ✅ Checking if we can deploy provider
pact/bin/pact-broker can-i-deploy \
                --pacticipant GoUserService \
                --broker-base-url http://localhost:8081 \
                --broker-username pact_workshop \
                --broker-password pact_workshop \
                --version d454a6437dfe75f0a9d94b082c6b154cb9d31cd2 \
                --to-environment production
Computer says yes \o/ 

There are no missing dependencies
```

**Comment by YOU54F** [comment]
You need to run `make provider` to run the provider verification task when retrieving the pact from the broker, after the publish step

https://github.com/pact-foundation/pact-workshop-go?tab=readme-ov-file#provider

**Comment by YOU54F** [comment]
a provider is able to deploy if it has no consumers.

a consumer isn't able to deploy as a pact has been created between the consumer and provider, but the provider has yet to verify it, and therefore the consumer doesn't know whether the consumer is compatible and effectively if the provider verification has not been run, against a pact from the broker, the provider is unaware of that consumer, and that consumers version that wishes to be deployed.

There are two ways that the pact verification may be triggered, by pact url (where a consumer pact contents has changed and requires verification) or by consumer version selectors, which are utilised when a provider makes a change
