### ISSUE TITLE
config.mk SHELL set to bash not working

### ISSUE THREAD

**Issue by ahanafy** [pact-foundation/pact-workshop-go#4]
first line in config.mk has
`SHELL = "/bin/bash"`

When i run make commands, i get: 
`make: "/bin/bash": Command not found
make: *** [Makefile:6: foo] Error 127`

Suggest this line change to:
`SHELL := /bin/bash`

**Comment by ALTELMA** [comment]
More suggestions from me. In case using ZSH should use this line

```
SHELL := /usr/bin/zsh
```

**Comment by YOU54F** [comment]
Good catch, this caught me when creating a CI run to test the workshop post update. 

Will get this change applied across the steps.
