### ISSUE TITLE
make consumer not working in DOcker File

### ISSUE THREAD

**Issue by ravindradhaka** [pact-foundation/pact-workshop-go#7]
echo $pwd
$ make consumer
--- Installing Pact CLI dependencies
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[100](https://git.naspersclassifieds.com/panamera/fcg/service/dapi/-/jobs/14677668#L100) 7525k  100 7525k    0     0  10.7M      0 --:--:-- --:--:-- --:--:-- 17.6M
--- 🔨Running Consumer Pact tests 
go test -count=1 ./consumer/client -run 'TestClientPact'
go: finding github.com/pact-foundation/pact-go v1.7.1-0.20220627045253-94d333263e43
go: finding cloud.google.com/go v0.46.3
go: finding github.com/hashicorp/logutils v1.0.0
go: finding github.com/hashicorp/go-version v1.5.0
go: finding google.golang.org/api v0.13.0
go: finding golang.org/x/net v0.0.0-202[102](https://git.naspersclassifieds.com/panamera/fcg/service/dapi/-/jobs/14677668#L102)26172049-e18ecbb05110
go: finding github.com/stretchr/testify v1.7.4
go: finding golang.org/x/text v0.3.3
go: finding github.com/gorilla/websocket v1.4.2
go: finding github.com/stretchr/objx v0.4.0
go: finding golang.org/x/crypto v0.0.0-20210921155[107](https://git.naspersclassifieds.com/panamera/fcg/service/dapi/-/jobs/14677668#L107)-089bfa567519
go: finding github.com/gin-gonic/gin v1.7.7
go: finding gopkg.in/yaml.v3 v3.0.1
go: finding github.com/google/uuid v1.3.0
go: finding github.com/klauspost/compress v1.14.2
2022/07/04 10:59:17 [ERROR] service: /builds/panamera/fcg/service/dapi/pact/lib/ruby/bin/ruby: line 6: /builds/panamera/fcg/service/dapi/pact/lib/ruby/bin.real/ruby: No such file or directory
2022/07/04 10:59:27 [ERROR] Expected server to start < 10s. Timed out waiting for Mock Server to start on port 33561 - are you sure it's running?
2022/07/04 10:59:27 [ERROR] client: failed to wait for Mock Server: Expected server to start < 10s. Timed out waiting for Mock Server to start on port 33561 - are you sure it's running?
2022/07/04 10:59:27 Error on Verify: Post http://localhost:33561/interactions: dial tcp 127.0.0.1:33561: connect: connection refused
FAIL	frontiercargroup.org/dealer/consumer/client	10.027s
FAIL
make: *** [Makefile:210: consumer] Error 1
Running after_script
Running after script...
$ mv $GOPATH/pkg/mod .go-mod
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 2

giving this error @mefellows

**Comment by mefellows** [comment]
Please follow the issue template and provide a way to reproduce the issue. 

For example:

1. At this moment, you mentioned Docker but not what container you are using (a public one or one you created yourself) or how you ran the container
2. The actual step by step way to reproduce it. It must have code the maintainers can easily get, run and test

**Comment by YOU54F** [comment]
Closing due to lack of response, feel free to reopen with further information if possible, thanks
